#!/usr/bin/bash

#g++ -c -std=c++11 game.cpp && g++ game.o -o game -lsfml-graphics -lGL -lsfml-window -lsfml-system -lBox2D && ./game
g++ -std=c++11 game.cpp -o game -lsfml-graphics -lGL -lsfml-window -lsfml-system -lBox2D && ./game
